security:
    role_hierarchy:

        ROLE_USER:
            - IS_AUTHENTICATED_ANONYMOUSLY

        ROLE_ADMIN:
            - ROLE_USER

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

        ROLE_ALLOWED_TO_ADD_ARTICLE:
            - ROLE_USER

        ROLE_ALLOWED_TO_READ_OWN_ARTICLE:
            - ROLE_USER

        ROLE_ALLOWED_TO_EDIT_OWN_ARTICLE:
            - ROLE_USER

        ROLE_ALLOWED_TO_REMOVE_OWN_ARTICLE:
            - ROLE_USER

        ROLE_ALLOWED_TO_READ_ARTICLE:
            - ROLE_ALLOWED_TO_READ_OWN_ARTICLE

        ROLE_ALLOWED_TO_EDIT_ARTICLE:
            - ROLE_ALLOWED_TO_EDIT_OWN_ARTICLE

        ROLE_ALLOWED_TO_REMOVE_ARTICLE:
            - ROLE_ALLOWED_TO_REMOVE_OWN_ARTICLE

        ROLE_BASIC_ARTICLE_READER:
            - ROLE_ALLOWED_TO_READ_OWN_ARTICLE

        ROLE_BASIC_ARTICLE_EDITOR:
            - ROLE_BASIC_ARTICLE_READER
            - ROLE_ALLOWED_TO_ADD_ARTICLE
            - ROLE_ALLOWED_TO_EDIT_OWN_ARTICLE
            - ROLE_ALLOWED_TO_REMOVE_OWN_ARTICLE

        ROLE_PRIVILEGED_ARTICLE_READER:
            - ROLE_ALLOWED_TO_READ_ARTICLE

        ROLE_PRIVILEGED_ARTICLE_EDITOR:
            - ROLE_PRIVILEGED_ARTICLE_READER
            - ROLE_ALLOWED_TO_ADD_ARTICLE
            - ROLE_ALLOWED_TO_EDIT_ARTICLE
            - ROLE_ALLOWED_TO_REMOVE_ARTICLE
